### ISSUE TITLE
投票結果ページ

### ISSUE THREAD

**Issue by shuheiokuda0704** [matsueoss/hiyaoroshigo#13]
投票結果を大々的に表示するページ

- 酒の順位
 - 順位
 - 酒名
 - 点数は表示しない
- 同点の場合は酒ID(?)順

**Comment by mlspinylobster** [comment]
隠したいかもしれない

**Comment by shugo** [comment]
残タスク:

- [ ] デザインの適用
- [ ] 公開時刻の制御
