### ISSUE TITLE
システム管理者機能

### ISSUE THREAD

**Issue by shuheiokuda0704** [matsueoss/hiyaoroshigo#14]
システム管理者(フェスティバル主催者)向けの管理機能

- フェスティバル情報登録・編集
- お酒登録・編集

**Comment by shugo** [comment]
マスタ管理はtypusを使う想定ですが、5-0-unstableブランチなので何か問題があるかもしれません。
一応/adminが動くところまでは確認してcommitしてあります。

config/locales/typus.ja.ymlの翻訳が中途半端なので、続きは学生さんたちにおまかせで。
