### ISSUE TITLE
パスコード発行

### ISSUE THREAD

**Issue by shuheiokuda0704** [matsueoss/hiyaoroshigo#2]
- フェスティバル参加者分のパスコードを発行する
 - フェスティバル参加者の情報は Peatix から CSV でエクスポートする
- パスコードはシステムユニークとする

**Comment by mlspinylobster** [comment]
アルファベット大小6文字で被らないように150個シェルで作れば良い気がします

**Comment by mlspinylobster** [comment]
パスコードの属性
・チケット名(出発地点)
・チケット番号
