### ISSUE TITLE
パスコード認証

### ISSUE THREAD

**Issue by shuheiokuda0704** [matsueoss/hiyaoroshigo#3]
アプリ利用時にユーザに配布チケットに書かれたパスコードを入力してもらい、パスコード認証を行う

- パスコード入力ページ
- パスコード認証機能

**Comment by mlspinylobster** [comment]
1. Facebookでログイン (ユーザID = FBID)
2. パスコード入力 (ユーザIDとパスコードを関連づけ)
3. トランキーロネームなど、情報入力
