### ISSUE TITLE
FBアカウント連携

### ISSUE THREAD

**Issue by shuheiokuda0704** [matsueoss/hiyaoroshigo#4]
アプリ利用時にFBログインを必須とする。

- OmniAuth?
- アプリケーションID取得
- アプリはFBログイン必須

**Comment by shugo** [comment]
omniauthを使う想定で、Gemfileの設定とモデル（Drinker）の生成まではやってあります。

参考: http://qiita.com/ytkt/items/d78841f7dea5e29f38ee

**Comment by shugo** [comment]
細かい修正は入るかもしれませんが、いったんクローズします。
