### ISSUE TITLE
投票ページ

### ISSUE THREAD

**Issue by shuheiokuda0704** [matsueoss/hiyaoroshigo#8]
飲んだお酒に投票するページ

- 項目
 - 点数(5段階)
 - お酒名
 - 飲み方(冷、常、燗)
 - 飲んだお店
- 投票制限
 - 単位時間あたりの登録を制限する(今回機能としては不要だが、設計考慮しておきたい)
 - フェスティバル開催時間外の投票を制限する

**Comment by shugo** [comment]
残タスク:

- [ ] デザインの適用（とくにスター表示をかっこよく）
