### ISSUE TITLE
ユーザが飲んだお酒一覧ページ

### ISSUE THREAD

**Issue by shuheiokuda0704** [matsueoss/hiyaoroshigo#9]
ユーザが飲んだお酒を一覧表示するページ

- 項目
 - お酒
 - 飲み方(冷、常、燗)

**Comment by shogo-mitomo** [comment]
マイページにまとめて表示する https://prottapp.com/p/418440#/s/57d3e46e86e4656d209c4d7d

**Comment by shugo** [comment]
プロフィール画面になったのでこちらはクローズします。
