### ISSUE TITLE
プロフィルページ左上の戻る「＜」ボタン

### ISSUE THREAD

**Issue by hasumon** [matsueoss/hiyaoroshigo#91]
history.backをやめて、 `/restaurants/vote` に飛ばす

**Comment by shugo** [comment]
投票期限が過ぎた後は/restaurants/voteは/itstoolateにリダイレクトするようにしましたが、問題ないですかね？

**Comment by hasumon** [comment]
@shugo 
![](https://media.giphy.com/media/vMnuZGHJfFSTe/giphy.gif)

**Comment by shugo** [comment]
@hasumon 
Wayne's World! Wayne's World! Party time! Excellent!
（若者に通じなさそう）

**Comment by hasumon** [comment]
@shugo 
オースティンパワーズなら......通じないか
