### ISSUE TITLE
管理画面 /admin 以下にベーシック認証かける

### ISSUE THREAD

**Issue by hasumon** [matsueoss/hiyaoroshigo#92]
NginxよりもRailsレイヤでやってしまうほうが後々混乱しないと思います

**Comment by hasumon** [comment]
@shugo 一応個人情報預かるんで、ベーシック認証とID/PWをダブルでかけたいです

**Comment by shugo** [comment]
了解です。

**Comment by mlspinylobster** [comment]
できれば、Basic認証よりは盗聴から守られるDigest認証の方が良いと思います！

**Comment by shugo** [comment]
今回はhttps必須なのでbasic認証で行きたいと思います。
nginx側で設定しました。
